version: '3.8'

networks:
  default-network:
    driver: bridge

volumes:
  mongo-db-data:

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    volumes:
      - mongo-db-data:/data/db
    networks:
      - default-network

  ibx-cloud-config-server:
    container_name: ibx-cloud-config-server
    image: xaviiborra/ibx-cloud-config-server
    restart: on-failure
    # env_file: ./.env
    ports:
      - 8888:8888
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.profiles.active": "dev"
      }'
    networks:
      - default-network

  ibx-cloud-eureka:
    container_name: ibx-cloud-eureka
    depends_on:
      - ibx-cloud-config-server
    image: xaviiborra/ibx-cloud-eureka
    restart: on-failure
    # env_file: ./.env
    ports:
      - 8761:8761
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.profiles.active": "dev"
      }'
    networks:
      - default-network

  ibx-cloud-gateway:
    container_name: ibx-cloud-gateway
    depends_on:
      - ibx-cloud-config-server
      - ibx-cloud-eureka
    image: xaviiborra/ibx-cloud-gateway
    restart: on-failure
    # env_file: ./.env
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.profiles.active": "dev"
      }'
    networks:
      - default-network

  ibx-cloud-account:
    container_name: ibx-cloud-account
    depends_on:
      - mongodb
      - ibx-cloud-config-server
      - ibx-cloud-eureka
    image: xaviiborra/ibx-cloud-account
    restart: on-failure
    # env_file: ./.env
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.profiles.active": "dev"
      }'
    networks:
      - default-network